_target_: pytorch_lightning.Trainer

accelerator: gpu
devices: 2
num_nodes: 1
max_epochs: 1000
strategy: ddp_find_unused_parameters_false
precision: 32

gradient_clip_val: null
gradient_clip_algorithm: null

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: -1
log_every_n_steps: 2
